using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WindowsFormsApplication1.ProjectAssets.Backgrounds
{
    class Background
    {
        public bool istileset;
        public int tilewidth;
        public int tileheight;
        public int tilexoff;
        public int tileyoff;
        public int tilehsep;
        public int tilevsep;
        public bool HTile;
        public bool VTile;
        public int TextureGroups;
        public bool For3D;
        public int width;
        public int height;
        public string data;

        public String toString()
        {
            return "<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->" +
                    "<background>" +
                        "<istileset>" + istileset + "</istileset>" +
                        "<tilewidth>" + tilewidth + "</tilewidth>" +
                        "<tileheight>" + tileheight + "</tileheight>" +
                        "<tilexoff>" + tilexoff + "</tilexoff>" +
                        "<tileyoff>" + tileyoff + "</tileyoff>" +
                        "<tilehsep>" + tilehsep + "</tilehsep>" +
                        "<tilevsep>" + tilevsep + "</tilevsep>" +
                        "<HTile>" + HTile + "</HTile>" +
                        "<VTile>" + VTile + "</VTile>" +
                        "<TextureGroups>" +
                            "<TextureGroup0>0</TextureGroup0>" +
                        "</TextureGroups>" +
                        "<For3D>" + For3D + "</For3D>" +
                        "<width>" + width + "</width>" +
                        "<height>" + height + "</height>" +
                        "<data>" + data + "</data>" +
                    "</background>";
        }
    }
}
