using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WindowsFormsApplication1.ProjectAssets.Backgrounds
{
    class Background
    {
        public bool istileset;
        public int tilewidth;
        public int tileheight;
        public int tilexoff;
        public int tileyoff;
        public int tilehsep;
        public int tilevsep;
        public bool HTile;
        public bool VTile;
        public List<int> TextureGroups = new List<int>();
        public bool For3D;
        public int width;
        public int height;
        public string data;

        public override String ToString()
        {
            string textureGroup = "";
            int i = 0;
            foreach (int group in TextureGroups)
            {
                textureGroup += "    <TextureGroup" + i + ">" + group + "</TextureGroup" + i + ">\n";
                i++;
            }

            return "<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->\n" +
                    "<background>\n" +
                        "  <istileset>" + Convert.ToInt32(istileset) * -1 + "</istileset>\n" +
                        "  <tilewidth>" + tilewidth + "</tilewidth>\n" +
                        "  <tileheight>" + tileheight + "</tileheight>\n" +
                        "  <tilexoff>" + tilexoff + "</tilexoff>\n" +
                        "  <tileyoff>" + tileyoff + "</tileyoff>\n" +
                        "  <tilehsep>" + tilehsep + "</tilehsep>\n" +
                        "  <tilevsep>" + tilevsep + "</tilevsep>\n" +
                        "  <HTile>" + Convert.ToInt32(HTile) * -1 + "</HTile>\n" +
                        "  <VTile>" + Convert.ToInt32(VTile) * -1 + "</VTile>\n" +
                        "  <TextureGroups>\n" +
                            textureGroup +
                        "  </TextureGroups>\n" +
                        "  <For3D>" + Convert.ToInt32(For3D) * -1 + "</For3D>\n" +
                        "  <width>" + width + "</width>\n" +
                        "  <height>" + height + "</height>\n" +
                        "  <data>" + data + "</data>\n" +
                    "</background>";
        }
    }
}
