using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net;

namespace GMSMapEditor.ProjectAssets.Rooms
{
    public class Room
    {
        public string caption = "";
        public int width = 1024;
        public int height = 768;
        public int vsnap = 16;
        public int hsnap = 16;
        public int isometric = 0; //??
        public int speed = 30;
        public bool persistent = false;
        public int colour = 255;
        public bool showcolour = true;
        public string code = "";
        public bool enableViews = true;
        public bool clearViewBackground = false;
        public bool clearDisplayBuffer = true;
        public bool PhysicsWorld = false;
        public int PhysicsWorldTop = 0;
        public int PhysicsWorldLeft = 0;
        public int PhysicsWorldRight = 1024;
        public int PhysicsWorldBottom = 768;
        public int PhysicsWorldGravityX = 0;
        public int PhysicsWorldGravityY = 10;
        public double PhysicsWorldPixToMeters = 0.100000001490116;
        public MakerSettings makerSettings = new MakerSettings();
        public List<Background> backgrounds = new List<Background>();
        public List<View> views = new List<View>();
        public List<Instance> instances = new List<Instance>();
        public List<Tile> tiles = new List<Tile>();

        public override String ToString()
        {
            string backgroundsTag = "";
            string viewsTag = "";
            string instancesTag = "  <instances/>\n";
            string tilesTag = "  <tiles/>\n";

            if (instances.Count > 0)
            {
                instancesTag = "  <instances>\n";
                foreach (Instance instance in instances)
                {
                    instancesTag += "    <instance objName=\"" + instance.objName + "\" x=\"" + instance.x + "\" y=\"" + instance.y + "\" name=\"" + instance.name + "\" locked=\"" + Convert.ToInt32(instance.locked) * -1 + "\" code=\"" + instance.code + "\" scaleX=\"" + instance.scaleX + "\" scaleY=\"" + instance.scaleY + "\" colour=\"" + instance.colour + "\" rotation=\"" + instance.rotation + "\"/>\n";
                }
                instancesTag += "  </instances>\n";
            }

            if (tiles.Count > 0)
            {
                tilesTag = "  <tiles>\n";
                foreach (Tile tile in tiles)
                {
                    tilesTag += "    <tile bgName=\"" + tile.bgName + "\" x=\"" + tile.x + "\" y=\"" + tile.y + "\" w=\"" + tile.w + "\" h=\"" + tile.h + "\" xo=\"" + tile.xo + "\" yo=\"" + tile.yo + "\" id=\"" + tile.id + "\" name=\"" + tile.name + "\" depth=\"" + tile.depth + "\" locked=\"" + Convert.ToInt32(tile.locked) * -1 + "\" colour=\"" + tile.colour + "\" scaleX=\"" + tile.scaleX + "\" scaleY=\"" + tile.scaleY + "\"/>\n";
                }
                tilesTag += "  </tiles>\n";
            }

            backgroundsTag += "  <backgrounds>\n";
            foreach(Background background in backgrounds)
            {
                backgroundsTag += "    <background visible=\"" + Convert.ToInt32(background.visible) * -1 + "\" foreground=\"" + Convert.ToInt32(background.foreground) * -1 + "\" name=\"" + background.name + "\" x=\"" + background.x + "\" y=\"" + background.y + "\" htiled=\"" + Convert.ToInt32(background.htiled) * -1 + "\" vtiled=\"" + Convert.ToInt32(background.vtiled) * -1 + "\" hspeed=\"" + background.hspeed + "\" vspeed=\"" + background.vspeed + "\" stretch=\"" + Convert.ToInt32(background.stretch) * -1 + "\"/>\n";
            }
            backgroundsTag += "  </backgrounds>\n";

            viewsTag += "  <views>\n";
            foreach (View view in views)
            {
                viewsTag += "    <view visible=\"" + Convert.ToInt32(view.visible) * -1 + "\" objName=\"" + WebUtility.HtmlEncode(view.objName) + "\" xview=\"" + view.xview + "\" yview=\"" + view.yview + "\" wview=\"" + view.wview + "\" hview=\"" + view.hview + "\" xport=\"" + view.xport + "\" yport=\"" + view.yport + "\" wport=\"" + view.wport + "\" hport=\"" + view.hport + "\" hborder=\"" + view.hborder + "\" vborder=\"" + view.vborder + "\" hspeed=\"" + view.hspeed + "\" vspeed=\"" + view.vspeed + "\"/>\n";
            }
            viewsTag += "  </views>\n";

            return  "<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->\n" +
                    "<room>\n" +
                    "  <caption>" + caption + "</caption>\n" +
                    "  <width>" + width + "</width>\n" +
                    "  <height>" + height + "</height>\n" +
                    "  <vsnap>" + vsnap + "</vsnap>\n" +
                    "  <hsnap>" + hsnap + "</hsnap>\n" +
                    "  <isometric>" + isometric + "</isometric>\n" +
                    "  <speed>" + speed + "</speed>\n" +
                    "  <persistent>" + Convert.ToInt32(persistent) * -1 + "</persistent>\n" +
                    "  <colour>" + colour + "</colour>\n" +
                    "  <showcolour>" + Convert.ToInt32(showcolour) * -1 + "</showcolour>\n" +
                    "  <code>" + code + "</code>\n" +
                    "  <enableViews>" + Convert.ToInt32(enableViews) * -1 + "</enableViews>\n" +
                    "  <clearViewBackground>" + Convert.ToInt32(clearViewBackground) * -1 + "</clearViewBackground>\n" +
                    "  <clearDisplayBuffer>" + Convert.ToInt32(clearDisplayBuffer) * -1 + "</clearDisplayBuffer>\n" +
                    "  <makerSettings>\n" +
                    "    <isSet>" + Convert.ToInt32(makerSettings.isSet) * -1 + "</isSet>\n" +
                    "    <w>" + makerSettings.w + "</w>\n" +
                    "    <h>" + makerSettings.h + "</h>\n" +
                    "    <showGrid>" + Convert.ToInt32(makerSettings.showGrid) * -1 + "</showGrid>\n" +
                    "    <showObjects>" + Convert.ToInt32(makerSettings.showObjects) * -1 + "</showObjects>\n" +
                    "    <showTiles>" + Convert.ToInt32(makerSettings.showTiles) * -1 + "</showTiles>\n" +
                    "    <showBackgrounds>" + Convert.ToInt32(makerSettings.showBackgrounds) * -1 + "</showBackgrounds>\n" +
                    "    <showForegrounds>" + Convert.ToInt32(makerSettings.showForegrounds) * -1 + "</showForegrounds>\n" +
                    "    <showViews>" + Convert.ToInt32(makerSettings.showViews) * -1 + "</showViews>\n" +
                    "    <deleteUnderlyingObj>" + Convert.ToInt32(makerSettings.deleteUnderlyingObj) * -1 + "</deleteUnderlyingObj>\n" +
                    "    <deleteUnderlyingTiles>" + Convert.ToInt32(makerSettings.deleteUnderlyingTiles) * -1 + "</deleteUnderlyingTiles>\n" +
                    "    <page>" + makerSettings.page + "</page>\n" +
                    "    <xoffset>" + makerSettings.xoffset + "</xoffset>\n" +
                    "    <yoffset>" + makerSettings.yoffset + "</yoffset>\n" +
                    "  </makerSettings>\n" +
                    backgroundsTag +
                    viewsTag +
                    instancesTag +
                    tilesTag +
                    "  <PhysicsWorld>" + Convert.ToInt32(PhysicsWorld) * -1 + "</PhysicsWorld>\n" +
                    "  <PhysicsWorldTop>" + PhysicsWorldTop + "</PhysicsWorldTop>\n" +
                    "  <PhysicsWorldLeft>" + PhysicsWorldLeft + "</PhysicsWorldLeft>\n" +
                    "  <PhysicsWorldRight>" + PhysicsWorldRight + "</PhysicsWorldRight>\n" +
                    "  <PhysicsWorldBottom>" + PhysicsWorldBottom + "</PhysicsWorldBottom>\n" +
                    "  <PhysicsWorldGravityX>" + PhysicsWorldGravityX + "</PhysicsWorldGravityX>\n" +
                    "  <PhysicsWorldGravityY>" + PhysicsWorldGravityY + "</PhysicsWorldGravityY>\n" +
                    "  <PhysicsWorldPixToMeters>" + PhysicsWorldPixToMeters + "</PhysicsWorldPixToMeters>\n" +
                    "</room>";
        }
    }
}
