using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GMSMapEditor.ProjectAssets.Rooms
{
    public class Room
    {
        public string caption;
        public int width;
        public int height;
        public int vsnap;
        public int hsnap;
        public int isometric; //??
        public int speed;
        public bool persistent;
        public int colour;
        public bool showcolour;
        public string code;
        public bool enableViews;
        public bool clearViewBackground;
        public bool clearDisplayBuffer;
        public bool PhysicsWorld;
        public int PhysicsWorldTop;
        public int PhysicsWorldLeft;
        public int PhysicsWorldRight;
        public int PhysicsWorldBottom;
        public int PhysicsWorldGravityX;
        public int PhysicsWorldGravityY;
        public double PhysicsWorldPixToMeters;
        public MakerSettings makerSettings = new MakerSettings();
        public List<Background> backgrounds = new List<Background>();
        public List<View> views = new List<View>();
        public List<Instance> instances = new List<Instance>();
        public List<Tile> tiles = new List<Tile>();

        public override String ToString()
        {
            string instancesTag = "  <instances/>\n";
            string tilesTag = "  <tiles/>\n";

            if (instances.Count > 0)
            {
                instancesTag = "  <instances>\n";
                foreach (Instance instance in instances)
                {
                    instancesTag += "    <instance objName=\"" + instance.objName + "\" x=\"" + instance.x + "\" y=\"" + instance.y + "\" name=\"" + instance.name + "\" locked=\"" + Convert.ToInt32(instance.locked) * -1 + "\" code=\"" + instance.code + "\" scaleX=\"" + instance.scaleX + "\" scaleY=\"" + instance.scaleY + "\" colour=\"" + instance.colour + "\" rotation=\"" + instance.rotation + "\"/>\n";
                }
                instancesTag += "  </instances>\n";
            }

            if (tiles.Count > 0)
            {
                tilesTag = "  <tiles>\n";
                foreach (Tile tile in tiles)
                {
                    instancesTag += "    <tile bgName=\"" + tile.bgName + "\" x=\"" + tile.x + "\" y=\"" + tile.y + "\" w=\"" + tile.w + "\" h=\"" + tile.h + "\" xo=\"" + tile.xo + "\" yo=\"" + tile.yo + "\" id=\"" + tile.id + "\" name=\"" + tile.name + "\" depth=\"" + tile.depth + "\" locked=\"" + Convert.ToInt32(tile.locked) * -1 + "\" colour=\"" + tile.colour + "\" scaleX=\"" + tile.scaleX + "\" scaleY=\"" + tile.scaleY + "\"/>\n";
                }
                instancesTag += "  </tiles>\n";
            }

            return  "<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->\n" +
                    "<room>\n" +
                    "  <caption>" + caption + "</caption>\n" +
                    "  <width>" + width + "</width>\n" +
                    "  <height>" + height + "</height>\n" +
                    "  <vsnap>" + vsnap + "</vsnap>\n" +
                    "  <hsnap>" + hsnap + "</hsnap>\n" +
                    "  <isometric>" + isometric + "</isometric>\n" +
                    "  <speed>" + speed + "</speed>\n" +
                    "  <persistent>" + Convert.ToInt32(persistent) * -1 + "</persistent>\n" +
                    "  <colour>" + colour + "</colour>\n" +
                    "  <showcolour>" + Convert.ToInt32(showcolour) * -1 + "</showcolour>\n" +
                    "  <code>" + code + "</code>\n" +
                    "  <enableViews>" + Convert.ToInt32(enableViews) * -1 + "</enableViews>\n" +
                    "  <clearViewBackground>" + Convert.ToInt32(clearViewBackground) * -1 + "</clearViewBackground>\n" +
                    "  <clearDisplayBuffer>" + Convert.ToInt32(clearDisplayBuffer) * -1 + "</clearDisplayBuffer>\n" +
                    "  <makerSettings>\n" +
                    "    <isSet>" + Convert.ToInt32(makerSettings.isSet) * -1 + "</isSet>\n" +
                    "    <w>" + makerSettings.w + "</w>\n" +
                    "    <h>" + makerSettings.h + "</h>\n" +
                    "    <showGrid>" + Convert.ToInt32(makerSettings.showGrid) * -1 + "</showGrid>\n" +
                    "    <showObjects>" + Convert.ToInt32(makerSettings.showObjects) * -1 + "</showObjects>\n" +
                    "    <showTiles>" + Convert.ToInt32(makerSettings.showTiles) * -1 + "</showTiles>\n" +
                    "    <showBackgrounds>" + Convert.ToInt32(makerSettings.showBackgrounds) * -1 + "</showBackgrounds>\n" +
                    "    <showForegrounds>" + Convert.ToInt32(makerSettings.showForegrounds) * -1 + "</showForegrounds>\n" +
                    "    <showViews>" + Convert.ToInt32(makerSettings.showViews) * -1 + "</showViews>\n" +
                    "    <deleteUnderlyingObj>" + Convert.ToInt32(makerSettings.deleteUnderlyingObj) * -1 + "</deleteUnderlyingObj>\n" +
                    "    <deleteUnderlyingTiles>" + Convert.ToInt32(makerSettings.deleteUnderlyingTiles) * -1 + "</deleteUnderlyingTiles>\n" +
                    "    <page>" + makerSettings.page + "</page>\n" +
                    "    <xoffset>" + makerSettings.xoffset + "</xoffset>\n" +
                    "    <yoffset>" + makerSettings.yoffset + "</yoffset>\n" +
                    "  </makerSettings>\n" +
                    "  <backgrounds>\n" +
                    "    <background visible=\"-1\" foreground=\"-1\" name=\"backgroundName\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"0\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "    <background visible=\"0\" foreground=\"0\" name=\"\" x=\"0\" y=\"0\" htiled=\"-1\" vtiled=\"-1\" hspeed=\"0\" vspeed=\"0\" stretch=\"0\"/>\n" +
                    "  </backgrounds>\n" +
                    "  <views>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "    <view visible=\"0\" objName=\"&lt;undefined&gt;\" xview=\"0\" yview=\"0\" wview=\"1024\" hview=\"768\" xport=\"0\" yport=\"0\" wport=\"1024\" hport=\"768\" hborder=\"32\" vborder=\"32\" hspeed=\"-1\" vspeed=\"-1\"/>\n" +
                    "  </views>\n" +
                    instancesTag +
                    tilesTag +
                    "  <PhysicsWorld>" + Convert.ToInt32(PhysicsWorld) * -1 + "</PhysicsWorld>\n" +
                    "  <PhysicsWorldTop>" + PhysicsWorldTop + "</PhysicsWorldTop>\n" +
                    "  <PhysicsWorldLeft>" + PhysicsWorldLeft + "</PhysicsWorldLeft>\n" +
                    "  <PhysicsWorldRight>" + PhysicsWorldRight + "</PhysicsWorldRight>\n" +
                    "  <PhysicsWorldBottom>" + PhysicsWorldBottom + "</PhysicsWorldBottom>\n" +
                    "  <PhysicsWorldGravityX>" + PhysicsWorldGravityX + "</PhysicsWorldGravityX>\n" +
                    "  <PhysicsWorldGravityY>" + PhysicsWorldGravityY + "</PhysicsWorldGravityY>\n" +
                    "  <PhysicsWorldPixToMeters>" + PhysicsWorldPixToMeters + "</PhysicsWorldPixToMeters>\n" +
                    "</room>";
        }
    }
}
